site_name: Swahilies for PHP
site_description: 'Swahilies bindings for PHP'
site_author: 'Alpha Olomi'
docs_dir: docs/
repo_name: 'alphaolomi/swahilies-php'
repo_url: 'https://github.com/alphaolomi/swahilies-php'
nav:
    - Home: index.md
theme:
  name: 'material'
  logo: 'logo.png'
  palette:
    primary: orange
